version: '3'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./frontend:/app

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

