services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile-frontend
    restart: unless-stopped
    ports:
      - "80:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile-backend
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgresql://postgres:df159357@db:5432/meme
    networks:
      - app-network

  db:
    build:
      context: ./db
      dockerfile: Dockerfile-db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=df159357
      - POSTGRES_DB=meme    
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
  
networks:
  app-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.21.0.0/16

volumes:
  postgres_data:


