version: '3'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./frontend:/app
    image: react-test-app_frontend:latest

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    image: react-test-app_backend:latest
    deploy:
      mode: replicated
      replicas: 1

